### ISSUE TITLE
Support thread safety analysis thru special attributes

### ISSUE THREAD

**Issue by KindDragon** [boostorg/thread#101]
Clang and MSVC
- Clang http://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
- MSVC Static Analyzer https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior

Would you merge PR with some of the attributes?

**Comment by viboes** [comment]
Hi, thanks for the pointers.

Yes, PR will be welcome.

I will suggest to provide some macros for Boost.Config that are used by Boost.Thread so that other libraries can profit of these macros.

**Comment by viboes** [comment]
Closed as no PR has been provided
