### ISSUE TITLE
shared_mutex perfomance on linux

### ISSUE THREAD

**Issue by kirillv** [boostorg/thread#115]
This question is based on 
https://svn.boost.org/trac/boost/ticket/11798
On linux mutex is used to guard iternal state of shared_mutex. Windows uses spinlocks instead. It would be great if on linux it would be the same as on windows (spinlocks).  Its not a bug, but an optimisation request. Thanks in advance.

**Comment by ned14** [comment]
Mutexes on linux use an internal spin count.

**Comment by viboes** [comment]
I recognize that the implementation is not as good as we would like.

Any complete patch improving the performances is welcome. We will need some probes of the improvement.

**Comment by viboes** [comment]
Close as there is no PR since more than 6 months
