### ISSUE TITLE
[Proposal] Add APIs for deferred set_value/exception

### ISSUE THREAD

**Issue by jamboree** [boostorg/thread#116]
As discussed on the mailing list:

http://lists.boost.org/boost-users/2017/02/87211.php

The proposal is to add these functions:
* `promise::set_value_deferred`
* `promise::set_exception_deferred`
* `promise::notify_deferred`

It's for finer-grain control. The existing `set_xxx_at_thread_exit` can thus be implemented in terms of these functions (where at thread-exit, it calls `notify_deferred` automatically).
This allows using the shared-state's storage w/o additional space overhead on the user side.

**Comment by viboes** [comment]
Here it is a PR https://github.com/boostorg/thread/pull/150.

Please, could you check if this is what you was expecting?

**Comment by jamboree** [comment]
Yes, looks what I expected. Thanks!
