### ISSUE TITLE
on_tls_prepare is broken under VS2017

### ISSUE THREAD

**Issue by pravic** [boostorg/thread#119]
Fixed in bd0379af57fa294df310221492da618844182658, but introduced in 206ff0ba7c8aba742222a341f7eba6571a392097.

So, Boost 1.63 and 1.62 are broken now. I wonder what was the reason to **introduce such check** and maintain it for every new compiler version?

**Comment by viboes** [comment]
Why do you say that these version were broken?
It is not clear to know what the new version would provide .

BTW, you now now a fix for the new compiler version :)

**Comment by pravic** [comment]
Because that check against _MSC_VER 1900 was introduced 9 months ago, so it was included in 1.62 and 1.63. Broken for VS 2017, of course.

Yes, now we have a fix, but we have to wait until 1.64 (until August?) to receive VS 2017 support. Especially because such checks exist in other boost libraries too.

**Comment by MarcelRaad** [comment]
The bad thing that I don't understand is that some future version with (_MSC_VER > 2000) will be broken again.

**Comment by pravic** [comment]
> instead of increment supported versions each release?

Well, except just increment supported compiler versions we need do not forget about it: [#11365](https://svn.boost.org/trac/boost/ticket/11365) appeared in 1.58 version, but was fixed only in [1.61](http://www.boost.org/users/history/version_1_61_0.html).

**Comment by viboes** [comment]
I'm maintaining as well as I can Boost.Thread. I have no idea of Windows.
If some one has a solution, please propose it, post a PR. 
To all of you that are interested. Please comment the PR.

I've requested help on Boost.Thread maintenance for windows several times already. If some one want to maintain this part of Boost, or even more please contact me directly.

**Comment by MarcelRaad** [comment]
> I'm maintaining as well as I can Boost.Thread.

Thanks for that!

> If some one has a solution, please propose it, post a PR.

I've posted a PR to just remove the never used codepath to avoid confusion and future breakage:
https://github.com/boostorg/thread/pull/120

**Comment by viboes** [comment]
Thanks, I will merge it once the release 1.64 is delivered.

**Comment by pravic** [comment]
Was it merged?

**Comment by MarcelRaad** [comment]
@pravic Yes, into the develop branch.

**Comment by viboes** [comment]
https://github.com/boostorg/thread/pull/120
