### ISSUE TITLE
basic_condition_variable::relocker::~relocker can throw an exception 

### ISSUE THREAD

**Issue by kalman5** [boostorg/thread#121]
relocker DTOR is implemented as the following:

                ~relocker()
                {
                    if(unlocked)
                    {
                        lock.lock();
                    }

                }

that lock.lock() can throw (see unique_lock::lock in lock_types.hpp) leading to std::terminate if compiled in c++11 mode

**Comment by viboes** [comment]
I don't see where `lock::lock()` can call to `std::terminate. It is because throw_exception can terminate?

IMO, the cases `lock::lock()` can throw can not occur in `~relocker as it is protected by `unlocked`.

Could you please elaborate when it can fail?

**Comment by viboes** [comment]
I will try to do the lock outside a destructor and propagate the exception.

Please could you tell me when do you see the call to terminate?

**Comment by viboes** [comment]
The problem I have are the exception warranties.
What will be the state when there is a failure when trying to lock?
The resource will be unusable. 
What the user should do when receiving an exception?


There are other uses similar to the relocker elsewhere in the library.

**Comment by kalman5** [comment]
You need to mark those exception as noexcept(false);

**Comment by viboes** [comment]
Ok, I see.

**Comment by viboes** [comment]
Done in boost 1.65.
