### ISSUE TITLE
Travis failures with std::thread

### ISSUE THREAD

**Issue by pdimov** [boostorg/thread#173]
The Travis jobs using the default g++ 4.8 installation fail with

```
gcc.compile.c++ bin.v2/libs/thread/test/ex_std_thread_guard.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/std_thread_guard.o
gcc.link bin.v2/libs/thread/test/ex_std_thread_guard.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/ex_std_thread_guard
gcc.compile.c++ bin.v2/libs/thread/test/ex_std_thread_guard_lib.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/std_thread_guard.o
gcc.link bin.v2/libs/thread/test/ex_std_thread_guard_lib.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/ex_std_thread_guard_lib
testing.capture-output bin.v2/libs/thread/test/ex_std_thread_guard_lib.test/gcc-gnu-4.8/debug/cxxstd-11/threadapi-pthread/threading-multi/ex_std_thread_guard_lib.run
====== BEGIN OUTPUT ======
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)

EXIT STATUS: 134
====== END OUTPUT ======
```

That's odd, I'm not sure what we need to do to "enable multithreading" there.

See f.ex. https://travis-ci.org/boostorg/boost/jobs/285103799

**Comment by pdimov** [comment]
Could be this bug: https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1228201

**Comment by viboes** [comment]
I've no idea what need to be done. I've never had such issue on the regression tests of multiple platforms and compilers.

I believe that it is the build system that enables multithreading with the threading=multi.

I would suggest to create an issue on the build system.

**Comment by viboes** [comment]
Yes, maybe it is the same bug.

For my side, I purpose to don't support this platform/compiler/version.

If some one has the time to see how to make it working, please send a PR.

**Comment by pdimov** [comment]
See #174.

**Comment by pdimov** [comment]
Works now. :-)

https://travis-ci.org/boostorg/boost/builds/285389334

**Comment by viboes** [comment]
Thanks
