### ISSUE TITLE
change ECMAScript value to Javascript (JavaScript is the original language)

### ISSUE THREAD

**Issue by jmichae3** [boostorg/thread#181]
change ECMAScript value to Javascript (JavaScript is original language)
JavaScript is a fuller language put out by Danny Goodman. it probably has a better regex spec.
he might be looking for a better publisher.
the other name is offending lots of developers, which are 1/4 the population.

**Comment by viboes** [comment]
?

**Comment by jmichae3** [comment]
the value std::regex::ECMAScript needs to be changed to std::regex::JavaScript in both the manuals, source file names, and source code for std::regex. JavaScript is the language's name. and you will probably find that the EBNF for JavaScript is not missing entries.

**Comment by viboes** [comment]
Please, could you point the files in Boost.Thread that are wrong?
I suspect you meant another library, isn't it?

**Comment by jmichae3** [comment]
are you the man responsible for std::regex, or are you another man?

**Comment by viboes** [comment]
I'm the maintainer of Boost.Thread and you have created this  issue in Boost.Thread not Boost.Regex. 

Closing this issue. Create one for Boost.Regex

**Comment by jmichae3** [comment]
sorry, this is in thread, should be in std::regex.
