### ISSUE TITLE
DOS support please (used in embedded, disk utilities)

### ISSUE THREAD

**Issue by jmichae3** [boostorg/thread#182]
should be functional in #if defined(DOS)&&(defined(WATCOMC)||defined(__MARSC)||defined(DJGPP)) compilers - all they have now is fsu pthreads and pth which I think are timer-based.
compiling for DOS requires a 32-bit Windows OS currently. maybe not for Mars C/C++.
please consider this.

**Comment by jmichae3** [comment]
DJGPP is a 32-bit compiler.

**Comment by viboes** [comment]
Why are you creating those issues in this repo?
