### ISSUE TITLE
can't put std::thread in vector of struct with other thread-related stuff, or class

### ISSUE THREAD

**Issue by jmichae3** [boostorg/thread#184]
try putting std::thread in struct and later trying to fill in blanks. it can't be done.
also, you have to CloseHandle() in windows when thread is done and people don't know this. which may explain any server resource leaks. that you can't do without a vector or array of struct.

- need to be able to instantiate an empty object at the start and fill in thread function and run it and
- maybe even close it later, even within a struct.
- constructor should not require running and configuring the thread upon instantiation.
- std::thread.nativeHandle() should allow someone to CloseHandle() on windows.

**Comment by viboes** [comment]
Why are you creating those issues in this repo?
