### ISSUE TITLE
Legal problem with `win32/thread_primitives.hpp`

### ISSUE THREAD

**Issue by pdimov** [boostorg/thread#209]
A third-party legal review has identified a problem as reported here:

https://lists.boost.org/Archives/boost/2018/02/241435.php

regarding

https://github.com/boostorg/thread/blob/526c72cb4b8e3cb14d6f8e008006ef36b2be2c39/include/boost/thread/win32/thread_primitives.hpp#L89-L110

introduced by

https://github.com/boostorg/thread/commit/04c53415fd0adc1921d419c54a1e5ec4b19917ea

The easiest way to fix that is to rewrite `GetTickCount64emulation` in terms of `boost::atomic_uint64_t`. As pointed out in

https://lists.boost.org/Archives/boost/2018/02/241453.php

an implementation already exists in Boost.Log:

https://github.com/boostorg/log/blob/1cc577cbf5fae8f55c71c4493a7ef89027bd85dc/src/timestamp.cpp#L66-L86

**Comment by viboes** [comment]
I missed the comment on this commit.

could someone provide a PR?

**Comment by pdimov** [comment]
@Lastique perhaps?

**Comment by Lastique** [comment]
I will make a PR shortly.

**Comment by viboes** [comment]
Thank you very much.
