### ISSUE TITLE
Does not work in the project c++ cli (0xc000007b)

### ISSUE THREAD

**Issue by jenokizm** [boostorg/thread#221]

**Comment by jenokizm** [comment]
The same version of the library tested in a normal project, works. But when moved code to a project С++ CLI WinForms when starting application showing messangebox error 0xc000007b. 
If
`#include <boost/thread.hpp>`
Get the error
![ashampoo_snap_2018 05 13_16h49m09s_001_](https://user-images.githubusercontent.com/11296510/39969209-7755189e-56e1-11e8-939e-892163022985.png)

**Comment by viboes** [comment]
Any PR fixing this configuration is welcome. I don't have access to Windows, neither the knowledge.

**Comment by jenokizm** [comment]
In fact, I read that the CLI does not support even the usual streams, your library repels from them so it can not work vprintsype. So there's nothing to fix, except how to push Microsoft to add threads to the CLI...

I think this topic can be closed
