### ISSUE TITLE
1.68 thread pool join do interruption

### ISSUE THREAD

**Issue by ohhmm** [boostorg/thread#226]
<img width="847" alt="screen shot 2018-08-04 at 11 05 44" src="https://user-images.githubusercontent.com/190779/43674077-88c9012c-97d6-11e8-9b85-fc3441fdc70e.png">

**Comment by viboes** [comment]
What do you suggest as behavior?

**Comment by ohhmm** [comment]
Call thread::join is good, do not interrupt.
If there is some need in interrupting then better to expose interrupt method.
Optional timeout parameter for join may be used to make possible to join first.

**Comment by viboes** [comment]
Ok, I will add `interrupt` and `join_and_interrupt`.
