### ISSUE TITLE
Compiling for ARM32/64 on VS2017 broken

### ISSUE THREAD

**Issue by DjArt** [boostorg/thread#233]
Due assign in interlocked_read.hpp:
```
        inline void* interlocked_read_acquire(void* volatile* x) BOOST_NOEXCEPT
        {
            void* const res=
#if defined(_M_ARM64)
                __iso_volatile_load64((const volatile __int64*)x);
#else
                __iso_volatile_load32((const volatile __int32*)x);
#endif
            BOOST_THREAD_DETAIL_COMPILER_BARRIER();
            __dmb(0xB); // _ARM_BARRIER_ISH, see armintr.h from MSVC 11 and later
            BOOST_THREAD_DETAIL_COMPILER_BARRIER();
            return res;
        }
```

**Comment by viboes** [comment]
Please, could you add the report you are getting?

**Comment by DjArt** [comment]
@viboes, sorry for the long wait. Error C2440: int can't be converted to void*.

**Comment by viboes** [comment]
Humm, if the function doesn't returns a void * why do we want to store it on a voir *?

**Comment by DjArt** [comment]
`void*` used as platform-unspecified(by size) pointer. So, I think that's better variant for saving original idea of code.

**Comment by viboes** [comment]
Oh, I see. 

So IIUC, __iso_volatile_load64 returned always a __int64 and __iso_volatile_load32 returned always __int32. 

And this size corresponds to the size of a pointer depending on whether _M_ARM64 is defined or not.

How it is that this worked before, Andrei, what do you think?

**Comment by DjArt** [comment]
I think, or this code was untested before, or MSVC for ARM has become more strict then before. x86/x86_64 compiler doesn't consider it as mistake.

**Comment by viboes** [comment]
I believe the code needs a static assert about the size of both types. Could you add it, please?
