### ISSUE TITLE
Resource leak @ https://github.com/boostorg/thread/blob/boost-1.61.0/include/boost/thread/detail/thread.hpp#L859

### ISSUE THREAD

**Issue by venjun2000** [boostorg/thread#261]
Issue location:
https://github.com/boostorg/thread/blob/boost-1.61.0/include/boost/thread/detail/thread.hpp#L859

Coverity tool detects and reports as major issue 

Resource leak    /DeliSpace/TegraP1Lin.Rel/External/Boost/inc/boost/thread/detail/thread.hpp    at_thread_exit

**Comment by viboes** [comment]
Thanks for the report. Have you analyzed the report? Are you sure there is a real leak? How are you sure this function 'thread_exit_func' is not called? isn't this a false positive?

**Comment by viboes** [comment]
I don't see from the report why there is a memory leak.

**Comment by venjun2000** [comment]
>>I don't see from the report why there is a memory leak.

Can you confirm whether there is leak or is it false positive ?    Is it something like the user of this library will free the storage allocated ? Is this library designed like this ?

**Comment by viboes** [comment]
The library free the storage at thread exit. Is Coverity checking it after the thread exits? IIUC Coverity is a static analysis tool, not a run-time one. I don't know how it can tell for sure that this function will not be called.

**Comment by austin-beer** [comment]
I ran `valgrind --leak-check=full test_thread_exit` (test_thread_exit.cpp is in the Boost.Thread test folder) against the latest develop branch and it reported that 0 bytes were leaked. The Coverity finding is a false positive. The memory is freed here:

https://github.com/boostorg/thread/blob/develop/src/pthread/thread.cpp#L104
