### ISSUE TITLE
Crash when calling interrupt() on a boost::thread, which has another boost::thread

### ISSUE THREAD

**Issue by elsamuko** [boostorg/thread#366]
Hi there,

I'm getting a crash when calling `interrupt()` on an outer `boost::thread`, which runs an inner `boost::thread`, which is connected to a `thread_guard`. It's not crashing when calling `join()` manually on the inner thread.

Crash:  
`terminate called after throwing an instance of 'boost::thread_interrupted'`

Source:  
https://gist.github.com/elsamuko/6e178c37fa2cf8742cb6bf512f2ff866

Compile & Run:  
http://coliru.stacked-crooked.com/a/46c512bf9a385fff

I'm running on Ubuntu 18.04. with g++ 7.5.0 and got the latest boost 1.78.0.

Let me know, if you need more information.
Regards,
Samuel

**Comment by sehe** [comment]
From my answer [here](https://stackoverflow.com/a/71486609/85371):

You're mixing std::thread and boost::thread.

Only boost::thread knows about interruption points. Use that to fix:

**[Live On Coliru](http://coliru.stacked-crooked.com/a/12ec130f579ef943)**

```c++
    #include <iostream>
    #include <thread>
    
    #include <boost/thread.hpp>
    #include <boost/thread/thread_guard.hpp>
    
    #define LOG(A) std::cout << A << std::endl;
    
    void double_interrupt() {
        boost::thread outer([] {
            boost::thread inner([] {
                while (true) {
                    boost::this_thread::sleep_for(boost::chrono::milliseconds(1));
                }
            });
    
            {
                boost::this_thread::sleep_for(boost::chrono::milliseconds(1));
                LOG("Interrupting inner");
    
                boost::thread_guard<boost::join_if_joinable> guard(
                    inner);
            }
        });
    
        LOG("Interrupting outer");
        outer.interrupt();
        outer.join();
    }
    
    int main() {
        LOG("Start");
    
        double_interrupt();
    
        LOG("End");
        return 0;
    }

```
Prints

    Start
    Interrupting outer
    End

**Comment by elsamuko** [comment]
@sehe `boost::sleep()` is an [interruption_point](https://www.boost.org/doc/libs/1_78_0/doc/html/thread/thread_management.html#thread.thread_management.tutorial.interruption), which I don't want in the inner loop. Imagine it as some work is done here.  
If you remove the sleep, it crashes again.

**Comment by sehe** [comment]
I'll continue the interaction at https://stackoverflow.com/a/71486609/85371 to prevent duplication.

**Comment by elsamuko** [comment]
I got a solution. It doesn't crash when using the `thread_guard` with a custom `struct non_interruptable_interrupt_and_join_if_joinable`:
```cpp
    // helper struct to interrupt a boost::thread within a boost::thread
    struct non_interruptable_interrupt_and_join_if_joinable {
        template <class Thread>
        void operator()(Thread& t) {
            if(t.joinable()) {
                boost::this_thread::disable_interruption di;
                t.interrupt();
                t.join();
            }
        }
    };
```

**Comment by pdimov** [comment]
Should be fixed with https://github.com/boostorg/thread/commit/f71e0f1645413c3291e37d766e5b04bc57c6e132 and https://github.com/boostorg/thread/commit/8db325363b8e91de23c062ec8964bb605ad89f11.
