### ISSUE TITLE
queue_back_view: documentation mismatch

### ISSUE THREAD

**Issue by cinghiale** [boostorg/thread#99]
The documentation says that `queue_back_view` supports  the [pull methods](https://github.com/boostorg/thread/blob/develop/doc/sync_queues_ref.qbk#L773) while they are not present in the implementation.

**Comment by viboes** [comment]
Thanks for caching this error in the documentation.

A queue_back/front_view are useful to split the push and the pull functionalities.

I will try to fix it for the next version.

**Comment by viboes** [comment]
https://github.com/boostorg/thread/commit/866ff746ae6b5c90c29dde7323fd5d6f36adbb30
